"""Add smart alert and product features

Revision ID: 6f63e51ca389
Revises: 0002_enterprise_intelligence
Create Date: 2026-05-17 09:48:33.989588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f63e51ca389'
down_revision: Union[str, None] = '0002_enterprise_intelligence'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Keep this migration additive. Older generated output attempted to drop
    # price_daily_analytics and many indexes, which can fail on MySQL when
    # existing constraints depend on those indexes. The runtime contract only
    # needs these new fields to exist.
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def has_column(table_name: str, column_name: str) -> bool:
        return any(column["name"] == column_name for column in inspector.get_columns(table_name))

    def add_column_if_missing(table_name: str, column: sa.Column) -> None:
        if not has_column(table_name, column.name):
            op.add_column(table_name, column)

    add_column_if_missing('alerts', sa.Column('percentage_drop', sa.Numeric(precision=5, scale=2), nullable=True))
    add_column_if_missing('alerts', sa.Column('price_lowest_in_x_days', sa.Integer(), nullable=True))
    add_column_if_missing('product_links', sa.Column('scrape_status', sa.String(length=20), server_default='PENDING', nullable=False))
    add_column_if_missing('product_links', sa.Column('error_message', sa.Text(), nullable=True))
    add_column_if_missing('products', sa.Column('lowest_price', sa.Numeric(precision=12, scale=2), nullable=True))
    add_column_if_missing('products', sa.Column('highest_price', sa.Numeric(precision=12, scale=2), nullable=True))

    # Existing deployments may already have the useful indexes under older
    # names. Do not drop them; create only the simple lookup indexes if absent.
    indexes_by_table = {
        table: {index["name"] for index in inspector.get_indexes(table)}
        for table in ("alerts", "product_links", "products")
        if table in inspector.get_table_names()
    }
    if 'ix_alerts_product_id' not in indexes_by_table.get('alerts', set()):
        op.create_index(op.f('ix_alerts_product_id'), 'alerts', ['product_id'], unique=False)
    if 'ix_alerts_user_id' not in indexes_by_table.get('alerts', set()):
        op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    if 'ix_product_links_product_id' not in indexes_by_table.get('product_links', set()):
        op.create_index(op.f('ix_product_links_product_id'), 'product_links', ['product_id'], unique=False)
    if 'ix_product_links_website_id' not in indexes_by_table.get('product_links', set()):
        op.create_index(op.f('ix_product_links_website_id'), 'product_links', ['website_id'], unique=False)
    return

    # ### commands auto generated by Alembic - kept below only for historical context. ###
    op.alter_column('alerts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_alerts_user_active', table_name='alerts')
    op.create_index(op.f('ix_alerts_product_id'), 'alerts', ['product_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.alter_column('brands', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('name', table_name='brands')
    op.drop_index('normalized_name', table_name='brands')
    op.drop_index('ix_brands_name', table_name='brands')
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.drop_index('ix_brands_normalized_name', table_name='brands')
    op.create_index(op.f('ix_brands_normalized_name'), 'brands', ['normalized_name'], unique=True)
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('name', table_name='categories')
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.alter_column('competitor_prices', 'captured_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_competitor_product_time', table_name='competitor_prices')
    op.drop_index('ix_competitor_website', table_name='competitor_prices')
    op.create_index(op.f('ix_competitor_prices_captured_at'), 'competitor_prices', ['captured_at'], unique=False)
    op.create_index(op.f('ix_competitor_prices_product_id'), 'competitor_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_competitor_prices_website_id'), 'competitor_prices', ['website_id'], unique=False)
    op.alter_column('discount_analysis', 'analyzed_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_discount_fake', table_name='discount_analysis')
    op.drop_index('ix_discount_product_time', table_name='discount_analysis')
    op.create_index(op.f('ix_discount_analysis_analyzed_at'), 'discount_analysis', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_discount_analysis_is_fake_discount'), 'discount_analysis', ['is_fake_discount'], unique=False)
    op.create_index(op.f('ix_discount_analysis_product_id'), 'discount_analysis', ['product_id'], unique=False)
    op.alter_column('ml_predictions', 'forecast_for',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('ml_predictions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_predictions_product_forecast', table_name='ml_predictions')
    op.create_index(op.f('ix_ml_predictions_forecast_for'), 'ml_predictions', ['forecast_for'], unique=False)
    op.create_index(op.f('ix_ml_predictions_product_id'), 'ml_predictions', ['product_id'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('price_history', 'captured_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_price_history_product_captured', table_name='price_history')
    op.create_index(op.f('ix_price_history_captured_at'), 'price_history', ['captured_at'], unique=False)
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.add_column('product_links', sa.Column('scrape_status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.add_column('product_links', sa.Column('error_message', sa.Text(), nullable=True))
    op.drop_index('ix_product_links_website', table_name='product_links')
    op.create_index(op.f('ix_product_links_product_id'), 'product_links', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_links_website_id'), 'product_links', ['website_id'], unique=False)
    op.alter_column('product_reviews', 'captured_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_reviews_product_time', table_name='product_reviews')
    op.create_index(op.f('ix_product_reviews_captured_at'), 'product_reviews', ['captured_at'], unique=False)
    op.create_index(op.f('ix_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.add_column('products', sa.Column('lowest_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('highest_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('products', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_products_category_brand', table_name='products')
    op.alter_column('purchases', 'purchased_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_purchases_user_time', table_name='purchases')
    op.create_index(op.f('ix_purchases_product_id'), 'purchases', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchases_purchased_at'), 'purchases', ['purchased_at'], unique=False)
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.alter_column('recommendation_logs', 'shown_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_recommendation_score', table_name='recommendation_logs')
    op.drop_index('ix_recommendation_user_product', table_name='recommendation_logs')
    op.create_index(op.f('ix_recommendation_logs_product_id'), 'recommendation_logs', ['product_id'], unique=False)
    op.alter_column('scraper_logs', 'scraped_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('search_history', 'searched_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('trend_analysis', 'calculated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_trend_direction', table_name='trend_analysis')
    op.drop_index('ix_trend_product_window', table_name='trend_analysis')
    op.create_index(op.f('ix_trend_analysis_calculated_at'), 'trend_analysis', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_trend_analysis_product_id'), 'trend_analysis', ['product_id'], unique=False)
    op.create_index(op.f('ix_trend_analysis_trend_direction'), 'trend_analysis', ['trend_direction'], unique=False)
    op.create_index(op.f('ix_trend_analysis_window'), 'trend_analysis', ['window'], unique=False)
    op.alter_column('user_preferences', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('ix_user_preferences_user', table_name='user_preferences')
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('email', 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.create_index('ix_user_preferences_user', 'user_preferences', ['user_id'], unique=False)
    op.alter_column('user_preferences', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_trend_analysis_window'), table_name='trend_analysis')
    op.drop_index(op.f('ix_trend_analysis_trend_direction'), table_name='trend_analysis')
    op.drop_index(op.f('ix_trend_analysis_product_id'), table_name='trend_analysis')
    op.drop_index(op.f('ix_trend_analysis_calculated_at'), table_name='trend_analysis')
    op.create_index('ix_trend_product_window', 'trend_analysis', ['product_id', 'window', 'calculated_at'], unique=False)
    op.create_index('ix_trend_direction', 'trend_analysis', ['trend_direction'], unique=False)
    op.alter_column('trend_analysis', 'calculated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('search_history', 'searched_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('scraper_logs', 'scraped_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_recommendation_logs_product_id'), table_name='recommendation_logs')
    op.create_index('ix_recommendation_user_product', 'recommendation_logs', ['user_id', 'product_id'], unique=False)
    op.create_index('ix_recommendation_score', 'recommendation_logs', ['score'], unique=False)
    op.alter_column('recommendation_logs', 'shown_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_purchased_at'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_product_id'), table_name='purchases')
    op.create_index('ix_purchases_user_time', 'purchases', ['user_id', 'purchased_at'], unique=False)
    op.alter_column('purchases', 'purchased_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.create_index('ix_products_category_brand', 'products', ['category_id', 'brand_id'], unique=False)
    op.alter_column('products', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_column('products', 'highest_price')
    op.drop_column('products', 'lowest_price')
    op.drop_index(op.f('ix_product_reviews_product_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_captured_at'), table_name='product_reviews')
    op.create_index('ix_reviews_product_time', 'product_reviews', ['product_id', 'captured_at'], unique=False)
    op.alter_column('product_reviews', 'captured_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_product_links_website_id'), table_name='product_links')
    op.drop_index(op.f('ix_product_links_product_id'), table_name='product_links')
    op.create_index('ix_product_links_website', 'product_links', ['website_id'], unique=False)
    op.drop_column('product_links', 'error_message')
    op.drop_column('product_links', 'scrape_status')
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_captured_at'), table_name='price_history')
    op.create_index('ix_price_history_product_captured', 'price_history', ['product_id', 'captured_at'], unique=False)
    op.alter_column('price_history', 'captured_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_ml_predictions_product_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_forecast_for'), table_name='ml_predictions')
    op.create_index('ix_predictions_product_forecast', 'ml_predictions', ['product_id', 'forecast_for'], unique=False)
    op.alter_column('ml_predictions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('ml_predictions', 'forecast_for',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_discount_analysis_product_id'), table_name='discount_analysis')
    op.drop_index(op.f('ix_discount_analysis_is_fake_discount'), table_name='discount_analysis')
    op.drop_index(op.f('ix_discount_analysis_analyzed_at'), table_name='discount_analysis')
    op.create_index('ix_discount_product_time', 'discount_analysis', ['product_id', 'analyzed_at'], unique=False)
    op.create_index('ix_discount_fake', 'discount_analysis', ['is_fake_discount'], unique=False)
    op.alter_column('discount_analysis', 'analyzed_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_competitor_prices_website_id'), table_name='competitor_prices')
    op.drop_index(op.f('ix_competitor_prices_product_id'), table_name='competitor_prices')
    op.drop_index(op.f('ix_competitor_prices_captured_at'), table_name='competitor_prices')
    op.create_index('ix_competitor_website', 'competitor_prices', ['website_id'], unique=False)
    op.create_index('ix_competitor_product_time', 'competitor_prices', ['product_id', 'captured_at'], unique=False)
    op.alter_column('competitor_prices', 'captured_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_index('name', 'categories', ['name'], unique=True)
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_brands_normalized_name'), table_name='brands')
    op.create_index('ix_brands_normalized_name', 'brands', ['normalized_name'], unique=False)
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.create_index('ix_brands_name', 'brands', ['name'], unique=False)
    op.create_index('normalized_name', 'brands', ['normalized_name'], unique=True)
    op.create_index('name', 'brands', ['name'], unique=True)
    op.alter_column('brands', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_product_id'), table_name='alerts')
    op.create_index('ix_alerts_user_active', 'alerts', ['user_id', 'is_active'], unique=False)
    op.alter_column('alerts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_column('alerts', 'price_lowest_in_x_days')
    op.drop_column('alerts', 'percentage_drop')
    op.create_table('price_daily_analytics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('analytics_date', sa.DATE(), nullable=False),
    sa.Column('min_price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('max_price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('avg_price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('sample_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('volatility_score', mysql.DECIMAL(precision=8, scale=4), server_default=sa.text("'0.0000'"), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='price_daily_analytics_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_price_daily_product_date', 'price_daily_analytics', ['product_id', 'analytics_date'], unique=True)
    op.create_index('ix_price_daily_date', 'price_daily_analytics', ['analytics_date'], unique=False)
    # ### end Alembic commands ###
